
http://localhost:8081/

###
POST http://localhost:8081/register HTTP/1.1
content-type: application/json

{
    "name": "Mads",
    "email": "q111@lol.dk",
    "password": "123",
    "confirmPassword": "123"
}

###

POST http://localhost:8081/login HTTP/1.1
content-type: application/json

{
    "email": "m1@me.dk",
    "password": "11111111"
}

###
POST http://localhost:8081/add HTTP/1.1
content-type: application/json

{
    "url": "mbrodt.github.io",
    "likes": 5121,
    "comments": [{
        "content": "A very nice portfolio indeed!",
        "likes": 5
    }, {
        "content": "Loving the colors",
        "likes": 3
    }]
}

###
http://localhost:8081/portfolios